#!/usr/bin/env bash
docker run \
    -v $HOME/.log:/app/Logs:z \
    -v $HOME/.temp:/app/Temp:z \
    -v $HOME/Downloads:/app/Downloads:z \
    -v $HOME/.config/twinvine/wvd:/app/WVDs:z \
    -v $HOME/.config/twinvine/cookies:/app/packages/envied/src/Cookies:Z \
    -it twinvine bash -c "uv run envied dl --no-folder itv $@"
